[tool.poetry]
name = "aula"
version = "0.1.0"
description = ""
authors = ["GuhNasc gpaulino31@hotmail.com>"]
license = ""
readme = "README.md"

[tool.poetry.dependencies]
python = "3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
